### ISSUE TITLE
你有点6啊

### ISSUE THREAD

**Issue by wszqkzqk** [rekols/qq-music#1]
666666

**Comment by wszqkzqk** [comment]
大Qt无敌

**Comment by rekols** [comment]
先放一张美图，哈哈哈．

![_ _20170816001225](https://user-images.githubusercontent.com/9636382/29324690-9cd583be-8217-11e7-815e-3d848db4a9d6.png)

**Comment by wszqkzqk** [comment]
@rekols 不支持下载？

**Comment by rekols** [comment]
必须支持

**Comment by wszqkzqk** [comment]
@rekols 为何不用纯Qt？

**Comment by rekols** [comment]
纯qt还要造控件

**Comment by wszqkzqk** [comment]
造啊哈哈

**Comment by wszqkzqk** [comment]
DTK适用范围太窄了这是没办法的。
@rekols 这样会让Ubuntu很尴尬😁😁😁😄😄😄

**Comment by rekols** [comment]
Ubuntu可以装dtk啊，Windows都可以编译

**Comment by wszqkzqk** [comment]
@rekols Windows？！！

**Comment by wszqkzqk** [comment]
Ubuntu好像是可以直接编译使用😄😄😄😄

**Comment by wszqkzqk** [comment]
哪天有时间我也编译看看
对了，支不支持mpris dbus

**Comment by rekols** [comment]
没有写e

**Comment by wszqkzqk** [comment]
额😳。。。

**Comment by wszqkzqk** [comment]
我现在还没有用上，先问一下，音乐🎵下载到本地的路径能不能改。。。
